Feat/graph
hattrickkk/currency-tracker pull request #2
Opened 2024-07-25 15:05 UTC by hattrickkk

2024-07-25 18:41 UTC, xYerMikx requested changes

2024-07-25 18:41 UTC, xYerMikx commented on src/components/chart/index.tsx
> +
точно нужно тайпскрипту говорить, что не паримся за параметр контекста? без ! никак?

2024-07-25 18:41 UTC, xYerMikx commented on src/components/chartForm/index.tsx
> +                            <InputsGroup values={el} disabled key={el.id} removeExchange={this.removeExchangeByID} />
inputs?.map() можно наверное просто сделать и убрать проверку на длину

2024-07-25 18:41 UTC, xYerMikx commented on src/components/chartForm/index.tsx
> +                    <InputsGroup changeCurrentExchange={this.changeCurrentExchange} first />
а точно передавая так пропс first сработает ? не надо ли first={true}

2024-07-25 18:41 UTC, xYerMikx commented on src/components/chartForm/style.module.scss
> +			margin: 0 0 30px 0;
margin-bottom

2024-07-25 18:41 UTC, xYerMikx commented on src/components/chartForm/style.module.scss
> +					margin: 0 0 30px 0;
margin-bottom

2024-07-25 18:41 UTC, xYerMikx commented on src/components/currencyConversionBlock/index.tsx
> +            setFirstInputValue(prev => (REGEX_FLOAT_NUMBERS.test(value) ? value : prev))
кажись можно вынести в хелпер и переиспользовать на 37 строке или вынести все, что идет после `=>` и использовать на 26 и 34 ещё строках

2024-07-25 18:41 UTC, xYerMikx commented on src/components/currencyConversionBlock/index.tsx
> +                <Input id={INPUT_FROM_ID} value={firstInputValue} onChange={onInputChange} maxLength={10} />
а я смогу написать сюда 'dfkjsghodh'? Если да, то нужна валидация на числа

2024-07-25 18:41 UTC, xYerMikx commented on src/components/errorBoundary/index.tsx
> +                            </Link>
я думаю можно либо убрать Link и использовать useNavigate хук из роутер-дома и в онКлик передать функцию, которая будет использовать navigate(paths.home), либо убрать button и стилизовать Link как надо

2024-07-25 18:41 UTC, xYerMikx commented on src/components/errorBoundary/style.module.scss
> +			margin: 0 0 60px 0;
margin-bottom, ниже тоже

2024-07-25 18:41 UTC, xYerMikx commented on src/components/notificationModal/index.tsx
> +                <p className={styles.notification}>The chart was successfully built for 30 days!</p>
по-моему у тебя был вариант построить не только на 30 дней, передай сюда пропс daysCount

2024-07-25 18:41 UTC, xYerMikx commented on src/components/notificationModalContextProvider/index.tsx
> +}
а для чего ты используешь контекст вообще?

2024-07-25 18:41 UTC, xYerMikx commented on src/constants/chartOptions.ts
> +                borderColor: 'rgba(255, 255, 255, 0.3)',
в константы, чтобы ниже юзать

2024-07-25 18:41 UTC, xYerMikx commented on src/customTypes/routes.ts
> +    Elem: React.LazyExoticComponent<() => JSX.Element>
это такой тип нужен для элемента? ReactNode не подойдет?

2024-07-25 18:41 UTC, xYerMikx commented on src/ui/inputsGroup/index.tsx
> +                this.addID()
а обязательно каррирование использовать, можно же просто сделать addId = () => this.props... и потом передать как this.addId

2024-07-25 18:41 UTC, xYerMikx commented on src/ui/inputsGroup/index.tsx
> +                                />
тут я думаю тоже на инпут валидацию сделать по числам и добавить диапазон значений, который можно вводить (например от 100 до 200 условно)

2024-07-25 18:41 UTC, xYerMikx commented on src/utils/exchangeObjValidation.ts
> +}
каждый раз пересоздаёшь свою let, попробуй вместо forEach использовать reduce, указать nexExchange как дефолтное значение и переписать эту же логику в reduce

2024-07-25 18:41 UTC, xYerMikx commented on src/utils/getToday.ts
> +    return `${year}-${moth}-${day}`
а чего в одном месте String, в другом toString? + очепятка с moth и тип указывать не обязательно, тайпскрипт примитивы после срабатывания метода toString() отлично подтягивает

2024-07-25 19:23 UTC, hattrickkk commented on src/components/chartForm/index.tsx
> +                            <InputsGroup values={el} disabled key={el.id} removeExchange={this.removeExchangeByID} />
тут мне map нужен, один раз я использую InputsGroup без map для того, чтобы отрисовать поля для ввода. В inputs же хранятся значения, которые уже введены и влияют на график, значения выводятся тоже в InputsGroup, но уже с параметром disabled, поэтому тут они отрисовываются через map

2024-07-25 19:26 UTC, hattrickkk commented on src/components/chartForm/index.tsx
> +                    <InputsGroup changeCurrentExchange={this.changeCurrentExchange} first />
у меня все работает, first используется в компоненте для условного рендеринга иконки удаления (чтобы "Х" не было возле полей для ввода, а только возле введенных значений)

2024-07-25 19:29 UTC, hattrickkk commented on src/components/chartForm/style.module.scss
> +			margin: 0 0 30px 0;
снова случайно проскочил ;((( 
это уже привычка, постепенно отучаюсь

2024-07-25 19:31 UTC, hattrickkk commented on src/components/currencyConversionBlock/index.tsx
> +                <Input id={INPUT_FROM_ID} value={firstInputValue} onChange={onInputChange} maxLength={10} />
нет, в onchange это как раз проверяется

2024-07-25 19:35 UTC, hattrickkk commented on src/components/notificationModal/index.tsx
> +                <p className={styles.notification}>The chart was successfully built for 30 days!</p>
в требованиях было написано оповещать, если 30 дней, поэтому я подумала, что так и нужно сделать. тогда переделаю.
получается, что у меня модалка будет появляться, когда я нажимаю на 2 кнопки (сгенерировать 30 и 15 дней) и в том случае, если я вручную 30 раз добавлю значения, верно?

2024-07-25 19:37 UTC, hattrickkk commented on src/components/notificationModalContextProvider/index.tsx
> +}
чтобы в компоненте с графиком в методе update открывать модалку, когда срабатывает оповещение

2024-07-25 19:47 UTC, hattrickkk commented on src/customTypes/routes.ts
> +    Elem: React.LazyExoticComponent<() => JSX.Element>
там из-за использования lazy() не подходят ReactElement или ReactNode, но нашла сейчас другой тип `ComponentType`, выглядит лучше, чем было

2024-07-25 19:51 UTC, hattrickkk commented on src/ui/inputsGroup/index.tsx
> +                this.addID()
можно....
это я тут перемудрила :D

2024-07-25 20:01 UTC, hattrickkk commented on src/components/chart/index.tsx
> +
без ! , оказывается, можно
но без указывания типа нет, или так, или при использовании this.context через as

2024-07-25 20:13 UTC, xYerMikx commented on src/components/notificationModal/index.tsx
> +                <p className={styles.notification}>The chart was successfully built for 30 days!</p>
ну да, давай сделаем так, на 15 и на 30 дней пускай будет и передашь текущее количество дней, на которое сгенерирован график

2024-07-25 20:16 UTC, xYerMikx commented on src/components/notificationModalContextProvider/index.tsx
> +}
хм, как вариант, просто ещё есть интересный подход с HOC, куда ты можешь через пропсы в свой компонент передать нужные параметры и в классовом уже спокойно использовать в твоём update через this.props.openModal()

2024-07-26 16:05 UTC, xYerMikx commented on src/ui/input/index.tsx
> +const Input = forwardRef(({ value, id, onChange, maxLength, placeholder }: Props, ref) => {
попробуй сделать дженерик forwardRef<InputHandle, Props> и тогда может as снизу не надо будет юзать

2024-07-26 16:05 UTC, xYerMikx commented on src/ui/input/index.tsx
> +                resetValue: () => {
раз уж в первом случае без return сокращенно, то давай и ниже сократим все записи

2024-07-26 16:05 UTC, xYerMikx commented on src/utils/exchangeObjValidation.ts
> +    return Object.keys(current).reduce((acum, key) => {
тут можно попробовать сразу типизацию в коллбеке прописать и тогда от as получится избавиться

2024-07-26 16:07 UTC, hattrickkk commented on src/ui/input/index.tsx
> +                resetValue: () => {
а я так и сделала в начале, но eslint ругался, мол функция, которая что-то возвращает должна иметь return. Поэтому так сделала. тогда будет лучше это правило отключить и все в одном стиле сделать?

2024-07-26 16:09 UTC, xYerMikx commented on src/ui/input/index.tsx
> +                resetValue: () => {
а как тогда сверху сработало? getValue: () => inputRef.current.value не работает?

2024-07-26 16:13 UTC, hattrickkk commented on src/ui/input/index.tsx
> +                resetValue: () => {
оно работает, но esLint визуально ругался
я тогда просто отключу правило и все будет нормально

2024-07-26 16:34 UTC, xYerMikx approved these changes

2024-07-27 12:06 UTC, merged